### ISSUE TITLE
txfonts 사용시 xetexko가 함께 호출되면 등호의 글꼴이 바뀌지 않음

### ISSUE THREAD

**Issue by mcpark3141** [dohyunkim/xetexko#4]
아래 코드에서 xetexko를 사용했을 경우와 사용하지 않을 경우 등호에 다른 글꼴이 적용되는 것 같습니다.

-------------------------------------------------------
\documentclass{article}
\usepackage{xetexko}
\usepackage{txfonts}

\begin{document}
$a = b$

$a \ne b$
\end{document}

**Comment by dohyunkim** [comment]
fontspec 매뉴얼 3.1절에 다음 내용이 씌여 있습니다:

> If you find that fontspec is incorrectly changing the maths font when it should be leaving well enough alone, apply the [no-math] package option to manually suppress its maths font.

따라서 xetexko를 부르기 전에 fontspec을 저 옵션과 함께 미리 불러오면 문제가 해결됩니다.
```
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{xetexko}
\usepackage{txfonts}
\begin{document}
$a = b$

$a \ne b$
\end{document}
```

**Comment by mcpark3141** [comment]
문제가 잘 해결되었습니다. 감사합니다.
